-- AlterTable
ALTER TABLE `profile` ADD COLUMN `storeAddress` VARCHAR(191) NULL,
    ADD COLUMN `storeName` VARCHAR(191) NULL,
    ADD COLUMN `storeType` ENUM('GROCERY', 'ELECTRONICS', 'CLOTHING', 'FURNITURE', 'RESTAURANT', 'OTHER') NULL;
